Repository martinmags/tft-analytics, pull requests merged in 2020-06, with the labels that each got.

#38 Just some maintenance stuff
  .gitignore
  README.md
  backend-server/README.md
  backend-server/requirements.txt
  backend-server/server.py
  backend-server/settings.py
Labels: Issue: Dependencies, Issue: Documentation

#46 Added new packages; added basic routing; created header component
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Header.js
  frontend/src/templates/HomePage.js
  frontend/src/templates/SummonerPage.js
Labels: Issue: Dependencies, Issue: New Feature

#47 LOL XD YIKES NO CAP
  frontend/src/components/Header.js
  frontend/src/index.js
  frontend/src/templates/SummonerPage.js
  package-lock.json
Labels: Issue: Bug

#55 Refactored Summoner Page and its subcomponents
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/ChampWithItemCard.js
  frontend/src/components/Champion.js
  frontend/src/components/ChampionList.js
  frontend/src/components/Header.js
  frontend/src/components/MatchHistoryCard.js
  frontend/src/components/MatchHistoryTabSelector.js
  frontend/src/components/MatchSummaryCard.js
  frontend/src/components/SummonerInfo.js
  frontend/src/components/SummonerNameCard.js
  frontend/src/components/SummonerRankCard.js
  frontend/src/components/Synergy.js
  frontend/src/templates/SummonerPage.js
Labels: Issue: Refactor

#57 Martin
  backend-server/server.py
  frontend/src/App.js
  frontend/src/components/ChampionList.js
  frontend/src/components/Header.js
  frontend/src/components/SearchBar.js
  frontend/src/components/SummonerInfo.js
  frontend/src/components/SummonerNameCard.js
  frontend/src/templates/SummonerPage.js
Labels: Issue: New Feature

#71 Martin
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/SummonerContext.js
  frontend/src/components/ChampionList.js
  frontend/src/components/Header.js
  frontend/src/components/SearchBar.js
  frontend/src/components/SummonerInfo.js
  frontend/src/components/SummonerNameCard.js
  frontend/src/components/SummonerRankCard.js
  frontend/src/hooks/HttpRequests.js
  frontend/src/templates/ErrorPage.js
  frontend/src/templates/HomePage.js
  frontend/src/templates/SummonerPage.js
Labels: Issue: New Feature, Issue: Refactor

#72 Zeke
  backend-server/server.py
  frontend/src/components/ChampionList.js
  frontend/src/components/MatchHistoryCard.js
  frontend/src/components/Synergy.js
  frontend/src/templates/SummonerPage.js
Labels: Issue: New Feature

#76 WATASHI NO MVP???? EHHH??YAAAAMETE!!?? ITAIII!!
  backend-server/server.py
  frontend/src/components/Champion.js
  frontend/src/components/ChampionList.js
  frontend/src/components/MatchHistoryCard.js
  frontend/src/templates/SummonerPage.js
Labels: Issue: New Feature

#79 EHHH?
  backend-server/server.py
  frontend/src/App.js
  frontend/src/components/Champion.js
  frontend/src/components/ChampionList.js
  frontend/src/components/MatchHistoryCard.js
  frontend/src/hooks/HttpRequest.js
  frontend/src/hooks/HttpRequestDependent.js
  frontend/src/hooks/HttpRequests.js
  frontend/src/templates/SummonerPage.js
Labels: Issue: Bug, Issue: New Feature

#78 MVP??
  .gitignore
  README.md
  backend-server/README.md
  backend-server/requirements.txt
  backend-server/server.py
  backend-server/settings.py
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/SummonerContext.js
  frontend/src/assets/icons/traits/Cybernetic.png
  frontend/src/assets/ranks/Emblem_Bronze.png
  frontend/src/assets/ranks/Emblem_Challenger.png
  frontend/src/assets/ranks/Emblem_Diamond.png
  frontend/src/assets/ranks/Emblem_Gold.png
  frontend/src/assets/ranks/Emblem_Grandmaster.png
  frontend/src/assets/ranks/Emblem_Iron.png
  frontend/src/assets/ranks/Emblem_Master.png
  frontend/src/assets/ranks/Emblem_Platinum.png
  frontend/src/assets/ranks/Emblem_Silver.png
  frontend/src/components/Champion.js
  frontend/src/components/ChampionList.js
  frontend/src/components/Header.js
  frontend/src/components/MatchHistoryCard.js
  frontend/src/components/MatchHistoryTabSelector.js
  frontend/src/components/SearchBar.js
  frontend/src/components/SummonerInfo.js
  frontend/src/components/SummonerNameCard.js
  frontend/src/components/SummonerRankCard.js
  frontend/src/components/Synergy.js
  frontend/src/components/UnrankedCard.js
  frontend/src/hooks/HttpRequest.js
  frontend/src/hooks/HttpRequestDependent.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/serviceWorker.js
  frontend/src/setupTests.js
  frontend/src/templates/ErrorPage.js
  frontend/src/templates/HomePage.js
  frontend/src/templates/SummonerPage.js
  package-lock.json
Labels: Issue: New Feature
